---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hustlogi/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R image $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
